# Generated by Django 3.1.1 on 2021-04-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myforum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproperties',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
