# Generated by Django 3.1.1 on 2021-04-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myforum', '0002_auto_20210423_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='banned',
            field=models.ManyToManyField(related_name='banned', to='myforum.UserProperties'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='moders',
            field=models.ManyToManyField(related_name='moders', to='myforum.UserProperties'),
        ),
    ]
