# Generated by Django 3.1.1 on 2021-05-02 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myforum', '0004_auto_20210502_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='banned',
            field=models.ManyToManyField(related_name='banned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='moders',
            field=models.ManyToManyField(related_name='moders', to=settings.AUTH_USER_MODEL),
        ),
    ]
