# Generated by Django 3.1.1 on 2021-05-14 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myforum', '0005_auto_20210502_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.date(2021, 5, 14)),
        ),
    ]
