# Generated by Django 3.1.1 on 2021-05-14 19:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myforum', '0006_auto_20210514_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 19, 52, 5, 51438, tzinfo=utc)),
        ),
    ]
