# Generated by Django 3.1.1 on 2021-05-14 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myforum', '0008_auto_20210514_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='rubric',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='user',
            new_name='author',
        ),
    ]
