# Generated by Django 3.1.1 on 2021-05-14 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myforum', '0009_auto_20210514_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='rubric',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='author',
            new_name='user',
        ),
    ]
