# Generated by Django 3.1.1 on 2021-05-18 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myforum', '0010_auto_20210514_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
