# Generated by Django 3.1.1 on 2021-05-18 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myforum', '0011_auto_20210518_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.date(2021, 5, 18)),
        ),
    ]
