# Generated by Django 3.1.1 on 2021-05-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myforum', '0015_remove_rubric_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproperties',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
