# Generated by Django 3.1.1 on 2021-05-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myforum', '0016_userproperties_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproperties',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
